export { default as MainPage } from "./MainPage.vue";
export { default as CatalogPage } from "./CatalogPage.vue";
export { default as ProductPage } from "./ProductPage.vue";
export { default as BagPage } from "./BagPage.vue";
export { default as FavoritesPage } from "./FavoritesPage.vue";
export { default as ContactPage } from "./ContactPage.vue";
export { default as OrderPage } from "./OrderPage.vue";
export { default as RegistrationPage } from "./RegistrationPage.vue";
export { default as EntrancePage } from "./EntrancePage.vue";
